port: ":3000" # 服务端口
log: # 日志
  max_size: 100 # mb
  max_backups: 10
  max_age: 10 # days
  level: "debug" # debug/info/warn/error
rate: # api 限流
  limit: 10 # 每秒发放的令牌数量，即每秒 10 个请求
  burst: 10 # 桶的容量
  reset_times: 60 # 重置时间，单位 秒
mysql: # 数据库
  host: "127.0.0.1"
  port: "3306"
  user_name: "root"
  password: "root"
  database: "bnqkl_chain_cms"
redis: # 缓存，全局锁
  host: "127.0.0.1"
  port: "6379"
  password: "Passw0rd"
  db: 1
  pool_size: 30
  min_idle_conn: 30
attach: # 文件存储
  blob: "blob"
